name: Emotes
main: me.superischroma.emotes.Emotes
version: 1.19
description: A chat-based emote plugin created for the WowieFreedom server. Express yourself!
author: Super_
commands:
    emotes:
        description: Information about Emotes
        usage: /<command> [list]
        aliases: em
    laugh:
        description: Laugh!
        usage: /<command> [player]
    raspberry:
        description: Blow a raspberry!
        usage: /<command> [player]
    dance:
        description: Do a dance!
        usage: /<command> [player]
    smile:
        description: Smile!
        usage: /<command> [player]
    cry:
        description: Cry.. cry away...
        usage: /<command> [player]
    grin:
        description: Smirkity smirk smirk!
        usage: /<command> [player]
    cheer:
        description: Cheeeer!
        usage: /<command> [player]
    backflip:
        description: Do a backflip!
        usage: /<command>
    greet:
        description: Greets everyone on the server!
        usage: /<command> [player]
    hug:
        description: Hug!
        usage: /<command> [player]
    kiss:
        description: Just a little smooch!
        usage: /<command> [player]
    highfive:
        description: Broosss!
        usage: /<command> [player]
    slap:
        description: Someone asleep? *SLAP*
        usage: /<command> [player]
    flip:
        description: Do a flip!
        usage: /<command> [player]
    eat:
        description: Eat a nice snack!
        usage: /<command> [player]
    tableflip:
        description: Mad? Flip a table!
        usage: /<command> [player]
    thumbsup:
        description: Give someone a thumbs up!
        usage: /<command> [player]
    pinch:
        description: Pinch! Ow!
        usage: /<command> [player]
